on:
  issues:
    types: [opened]

permissions:
  issues: write
  actions: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Rickroll
        uses: TejasvOnly/random-rickroll@v1.0
        with:
          percentage: 100
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
