on:
  issues:
    types: [opened]

permissions:
  issues: write   # Ensures the token can write to issues
  actions: write  # Sometimes external actions need action write permission

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Rickroll
        uses: TejasvOnly/random-rickroll@v1.0
        with:
          percentage: 100
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
